// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esgsjmubzunqxewlxswr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZ3NqbXVienVucXhld2x4c3dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTkzNTEsImV4cCI6MjA3MTkzNTM1MX0.YB7wfRYJaOV631sYR3riR9sVf-Ca55O7gBIX7F4nW9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});